FROM golang:1.16 AS base
MAINTAINER The Stripe Observability Team <support@stripe.com>

RUN mkdir /veneur /build
WORKDIR /veneur
COPY . .
RUN go build -a -v -ldflags "-X github.com/stripe/veneur.VERSION=$(git rev-parse HEAD)" -o /build/veneur ./cmd/veneur
RUN go build -a -v -ldflags "-X github.com/stripe/veneur.VERSION=$(git rev-parse HEAD)" -o /build/veneur-emit ./cmd/veneur-emit
RUN go build -a -v -ldflags "-X github.com/stripe/veneur.VERSION=$(git rev-parse HEAD)" -o /build/veneur-prometheus ./cmd/veneur-prometheus
RUN go build -a -v -ldflags "-X github.com/stripe/veneur.VERSION=$(git rev-parse HEAD)" -o /build/veneur-proxy ./cmd/veneur-proxy


FROM debian:sid AS release
RUN apt-get update && apt-get -y install ca-certificates
WORKDIR /veneur/
COPY --from=base /build/* /veneur/
COPY --from=base /veneur/example.yaml /veneur/config.yaml
COPY --from=base /veneur/example_proxy.yaml /veneur/config_proxy.yaml
ENV PATH="/veneur:${PATH}"
CMD ["/veneur/veneur", "-f", "config.yaml"]
